%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: D:\Users\danie\PycharmProjects\smartwatches_swimming_daniel\training\data\re_labeled\2020_03_05\cartner\1583406884650877184_N1.csv
%
% Auto-generated by MATLAB on 21-Mar-2020 12:54:53
close all; clear all;
%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 6);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ";";

% Specify column names and types
opts.VariableNames = ["timestamp", "type", "val1", "val2", "val3", "style"];
opts.VariableTypes = ["double", "categorical", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "type", "EmptyFieldRule", "auto");

% Import the data
tbl = readtable("D:\Users\danie\PycharmProjects\smartwatches_swimming_daniel\training\data\re_labeled\2020_03_05\cartner\1583406884650877184_N1.csv", opts);

%% Convert to output type
timestamp = tbl.timestamp;
type = tbl.type;
val1 = tbl.val1;
val2 = tbl.val2;
val3 = tbl.val3;
style = tbl.style;

%% Clear temporary variables
clear opts tbl
%%
close all;
acc_idx = find((type == 'ACC'));
acc_idx = acc_idx(1:end);

n = length(acc_idx);
fs = 104;
if mod(n,2)==0
    fshift = (-n/2:n/2-1)*(fs/n);
else
    fshift = (-(n-1)/2:(n-1)/2)*(fs/n);
end

ts_acc = timestamp(acc_idx);
ts_acc_std = (ts_acc-ts_acc(1))*length(ts_acc)/(ts_acc(end)-ts_acc(1));

unif_f = fftshift(fft(val1(acc_idx)));
nonunif_f = fftshift(nufft(val1(acc_idx),ts_acc_std));
%%
close all;figure;hold on;
plot(fshift,log10(abs(nonunif_f)),'rx');
plot(fshift,log10(abs(unif_f)),'b.');
axis tight; xlabel('Frequency [Hz]'); ylabel('log_{10}(abs(fft value))');
%%
close all;
if mod(n,2)==0
    conj_nonunif_f_side = (nonunif_f(find(fshift==0)+1:end)+flip(conj(nonunif_f(2:find(fshift==0)-1))))/2;
    conj_nonunif_f = [abs(nonunif_f(1)); conj(flip(conj_nonunif_f_side)); abs(nonunif_f(find(fshift==0))); conj_nonunif_f_side];
else
    conj_nonunif_f_side = (nonunif_f(find(fshift==0)+1:end)+flip(conj(nonunif_f(1:find(fshift==0)-1))))/2;
    conj_nonunif_f = [conj(flip(conj_nonunif_f_side)); abs(nonunif_f(find(fshift==0))); conj_nonunif_f_side];
end
plot(fshift, abs(conj_nonunif_f));

%%
unif_t = ifft(ifftshift(unif_f));
nonunif_t = ifft(ifftshift(conj_nonunif_f));
%%
close all;
figure;
plot(abs(unif_t-nonunif_t))
%%
figure;hold on;
plot((unif_t),'b.');
plot(nonunif_t,'rx');